model:
    train_mode: pushforward
    inference_mode: pushforward
    correlation: 0.8
    model_name: unet2d
    lr: 1.0e-5
    pushforward_steps: 1
    pushforward_grad: False
    warmup_epochs: 5
    fno2d:
        in_channels: 1
        out_channels: 1
        modes1: 12
        modes2: 12
        width: 48
        cond_channels: 48
        cond_dim: 0
        num_layers: 5
        time_scale: 1.0
        cond_scale: 1.0
        use_cond: False
    unet2d:
        n_input_scalar_components: 1
        n_input_vector_components: 0
        n_output_scalar_components: 1
        n_output_vector_components: 0
        time_history: 1
        time_future: 1
        hidden_channels: 32
        embedding_dim: 32
        cond_dim: 0
        ch_mults: [1, 2 ,4]
        use_scale_shift_norm: True
        time_scale: 1.0
        cond_scale: 1.0
        use_cond: False

data:
    dataset:
        train_path: /home/ayz2/temporal_pdes/data_processing/KolmFlow_train_1024.h5
        valid_path: /home/ayz2/temporal_pdes/data_processing/KolmFlow_valid_256.h5
        pde: km_flow
        resolution: [201, 160, 160]
    num_workers: 8
    batch_size: 8

training:
    seed: 42
    devices: 1
    accelerator: gpu
    check_val_every_n_epoch: 10
    log_every_n_steps: 64
    max_epochs: 250
    default_root_dir: logs/
    project: residual_pdes_rev
    wandb_mode: online
    checkpoint: null