model:
    train_mode: refiner
    inference_mode: refiner
    correlation: 0.8
    model_name: unet2d
    lr: 5.0e-4
    num_refinement_steps: 3
    min_noise_std: 4.0e-7
    fno2d:
        in_channels: 1
        out_channels: 1
        modes1: 12
        modes2: 12
        width: 48
        cond_channels: 48
        cond_dim: 3
        num_layers: 5
        time_scale: 10.0
        cond_scale: 10.0
    unet2d:
        n_input_scalar_components: 1
        n_input_vector_components: 0
        n_output_scalar_components: 1
        n_output_vector_components: 0
        time_history: 1
        time_future: 1
        hidden_channels: 32
        embedding_dim: 32
        cond_dim: 3
        ch_mults: [1, 2 ,4]
        use_scale_shift_norm: True
        time_scale: 10.0
        cond_scale: 10.0

data:
    dataset:
        train_path: /home/ayz2/data_gen_old/pde-context/2D/train/NEW_Burgers_1024.h5
        valid_path: /home/ayz2/data_gen_old/pde-context/2D/valid/NEW_Burgers_256.h5
        pde: burgers_2d
        resolution: [100, 64, 64]
    num_workers: 16
    batch_size: 64

training:
    seed: 42
    devices: 1
    accelerator: gpu
    check_val_every_n_epoch: 10
    log_every_n_steps: 64
    max_epochs: 500
    default_root_dir: logs/
    project: residual_pdes_final
    wandb_mode: online
    checkpoint: null