model:
    train_mode: refiner
    inference_mode: refiner
    correlation: 0.8
    model_name: unet
    lr: 1.0e-5
    num_refinement_steps: 3
    min_noise_std: 4.0e-7
    fno:
        in_channels: 1
        out_channels: 1
        modes: 32
        width: 64
        cond_channels: 64
        num_layers: 5
        time_scale: 1.0
        cond_scale: 10.0
        cond_dim: 0
        use_cond: False
    unet:
        n_input_scalar_components: 1
        n_input_vector_components: 0
        n_output_scalar_components: 1
        n_output_vector_components: 0
        time_history: 1
        time_future: 1
        hidden_channels: 64
        embedding_dim: 64
        ch_mults: [1, 2 ,4]
        use_scale_shift_norm: True
        time_scale: 1.0
        cond_scale: 10.0
        cond_dim: 0
        use_cond: False

data:
    dataset:
        train_path: /home/ayz2/data_gen_old/pde-context/1D/train/KS_train_4096_400.h5
        valid_path: /home/ayz2/data_gen_old/pde-context/1D/valid/KS_valid_256_400.h5
        pde: ks
        resolution: [200, 200] # nt, nx
        start: 0.5 # discard first 50% of data for burn-in
    num_workers: 16
    batch_size: 64

training:
    seed: 42
    devices: 1
    accelerator: gpu
    check_val_every_n_epoch: 10
    max_epochs: 250
    default_root_dir: logs/
    project: residual_pdes_final
    wandb_mode: online
    checkpoint: null